blueprint:
  name: "AWTRIX DPC Alert - Clear App 🗑️"
  description:
    "Removes the DPC Alert app from all configured AWTRIX devices.\n\n
    This blueprint creates an automation that can be manually triggered to remove
    the DPC Alert application from all AWTRIX devices.\n\n
    Useful for testing or when you want to clean up the display."
  domain: automation
  input:
    awtrix:
      name: AWTRIX Device
      description: Select the AWTRIX devices from which to remove the app
      selector:
        device:
          integration: mqtt
          manufacturer: Blueforcer
          model: AWTRIX 3
          multiple: true

mode: single

variables:
  device_ids: !input awtrix
  app_topic: "dpc_alert"
  devices_topics: |
    {%- macro get_device_topic(device_id) %}
      {{ states((device_entities(device_id) | select('search','device_topic') | list)[0]) }}
    {%- endmacro %}
    {%- set ns = namespace(devices=[]) %}
    {%- for device_id in device_ids %}
      {%- set device=get_device_topic(device_id)|replace('','') %}
      {% set ns.devices = ns.devices + [ device ~ '/custom/' ~ app_topic] %}
    {%- endfor %}
    {{ ns.devices | reject('match','unavailable') | list }}

trigger: []

condition: []

action:
  - repeat:
      for_each: "{{ devices_topics }}"
      sequence:
        - service: mqtt.publish
          data:
            qos: 0
            retain: false
            topic: "{{ repeat.item }}"
            payload: ""

  - service: system_log.write
    data:
      message: "DPC Alert app cleared from {{ devices_topics|length }} AWTRIX device(s)"
      level: info
